# Generated by Django 3.0.7 on 2020-06-12 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reference', '0003_reference_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reference',
            options={'ordering': ('-publish',)},
        ),
        migrations.AddField(
            model_name='reference',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
